import type { Metadata } from "next";
//import { DM_Sans } from "next/font/google";
import "./globals.css";
import Providers from "./Providers";

// components
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Jooble-Nextjs-14",
  description: "Generated by create next app",
};

// const font_family = DM_Sans({
//   subsets: ["latin"],
//   weight: ["400", "500", "600", "700", "800", "900", "1000"],
// });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        //className={font_family.className}
        suppressHydrationWarning={true}
      >
        <main>
          <Providers>
            <Navbar />
            {children}
            <Footer />
          </Providers>
        </main>
      </body>
    </html>
  );
}
